### ISSUE TITLE
Customize announcement/accessibility divs to avoid `validateDOMNesting(...)` warnings.

### ISSUE THREAD

**Issue by OmarOmeiri** [clauderic/dnd-kit#899]
I have sortable table headers, but the announcement divs should not be placed as siblings to the `<th/>` elements.

This could be solved by:

1. Customizing the location of the divs
2. Removing them altogether and recreating them manually outside the `<th/>` elements
3. Ability to change the default `<divs/>` to another tag

Is there a way to achieve any of this?

```html
<table class="Table_Table__HqHVi" style="width:900px">
  <thead style="">
    <tr>
      <th style="width: 150px;" class="Header_Th__n_MV9 Header_Sortable__xd2cM" colspan="1">
        ...
      </th>
      <th style="width: 150px;" class="Header_Th__n_MV9 Header_Sortable__xd2cM" colspan="1">
        ...
      </th>
      <th style="width: 150px;" class="Header_Th__n_MV9 Header_Sortable__xd2cM" colspan="1">
        ...
      </th>
      <th style="width: 150px;" class="Header_Th__n_MV9 Header_Sortable__xd2cM" colspan="1">
        ...
      </th>
      <th style="width: 150px;" class="Header_Th__n_MV9 Header_Sortable__xd2cM" colspan="1">
        ...
      </th>
      <th style="width: 150px;" class="Header_Th__n_MV9 Header_Sortable__xd2cM" colspan="1">
        ...
      </th>
       <!-- SHOULD NOT BE HERE -->
      <div id="DndDescribedBy-1" style="display: none;">
        To pick up a draggable item, press the space bar.
        While dragging, use the arrow keys to move the item.
        Press space again to drop the item in its new position, or press escape to cancel.
      </div>
       <!-- SHOULD NOT BE HERE -->
      <div id="DndLiveRegion-1" role="status" aria-live="assertive" aria-atomic="true"
        style="position: fixed; width: 1px; height: 1px; margin: -1px; border: 0px; padding: 0px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); clip-path: inset(100%); white-space: nowrap;">
        Draggable item firstName was dropped over droppable area firstName</div>
    </tr>
  </thead>
  <tbody>
    ...
  </tbody>
  <tfoot>
    <tr>
      ...
    </tr>
  </tfoot>
</table>
```

```diff
- Warning: validateDOMNesting(...): <div> cannot appear as a child of <tr>.
-    at div
-    at HiddenText (webpack-internal:///./node_modules/@dnd-kit/accessibility/dist/accessibility.esm.js:16:5)
-    at Accessibility (webpack-internal:///./node_modules/@dnd-kit/core/dist/core.esm.js:127:5)
-    at DndContext (webpack-internal:///./node_modules/@dnd-kit/core/dist/core.esm.js:2861:5)
...
```

**Comment by receptiryaki** [comment]
I can't find any documentation about this, but I found an option in typings for container element. 

You can set different container like this.

`<DndContext accessibility={{ container: document.body }}>`
